# goreleaser config for potctl. See: https://goreleaser.com
#
# To execute goreleaser, use the mage targets:
#
#  $ mage potctl:snapshot
#  $ mage potctl:release
#
# The snapshot target builds the installation packages (brew, rpm,
# deb, etc), into the dist dir.
# The release target does the same, but also publishes the packages.
#
# See README.md for more.
version: 2
project_name: potctl
env:
  - GO111MODULE=on
  - CGO_ENABLED=0
before:
  hooks:
    - go version

builds:
  - id: build_macos
    binary: potctl
    env:
    main: ./cmd/potctl/main.go
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X "github.com/datasance/potctl/pkg/util.versionNumber=v{{.Version}}"
      - -s -w -X "github.com/datasance/potctl/pkg/util.commit={{ .ShortCommit }}"
      - -s -w -X "github.com/datasance/potctl/pkg/util.date={{.Date}}"
      - -s -w -X "github.com/datasance/potctl/pkg/util.platform={{.Os}}/{{.Arch}}"
      - -s -w -X "github.com/datasance/potctl/pkg/util.operatorTag=3.5.1"
      - -s -w -X "github.com/datasance/potctl/pkg/util.routerAdaptorTag=3.5.0"
      - -s -w -X "github.com/datasance/potctl/pkg/util.routerTag=3.5.1"
      - -s -w -X "github.com/datasance/potctl/pkg/util.controllerTag=3.5.6"
      - -s -w -X "github.com/datasance/potctl/pkg/util.agentTag=3.5.2"
      - -s -w -X "github.com/datasance/potctl/pkg/util.controllerVersion=3.5.6"
      - -s -w -X "github.com/datasance/potctl/pkg/util.agentVersion=3.5.2"
      - -s -w -X "github.com/datasance/potctl/pkg/util.repo=ghcr.io/datasance"

  - id: build_linux
    binary: potctl
    main: ./cmd/potctl/
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 6
      - 7
    ldflags:
      - -extldflags -static
      - -s -w -X "github.com/datasance/potctl/pkg/util.versionNumber=v{{.Version}}"
      - -s -w -X "github.com/datasance/potctl/pkg/util.commit={{ .ShortCommit }}"
      - -s -w -X "github.com/datasance/potctl/pkg/util.date={{.Date}}"
      - -s -w -X "github.com/datasance/potctl/pkg/util.platform={{.Os}}/{{.Arch}}"
      - -s -w -X "github.com/datasance/potctl/pkg/util.operatorTag=3.5.1"
      - -s -w -X "github.com/datasance/potctl/pkg/util.routerAdaptorTag=3.5.0"
      - -s -w -X "github.com/datasance/potctl/pkg/util.routerTag=3.5.1"
      - -s -w -X "github.com/datasance/potctl/pkg/util.controllerTag=3.5.6"
      - -s -w -X "github.com/datasance/potctl/pkg/util.agentTag=3.5.2"
      - -s -w -X "github.com/datasance/potctl/pkg/util.controllerVersion=3.5.6"
      - -s -w -X "github.com/datasance/potctl/pkg/util.agentVersion=3.5.2"
      - -s -w -X "github.com/datasance/potctl/pkg/util.repo=ghcr.io/datasance"

    flags:
      - -v

  - id: build_windows
    binary: potctl
    env:
    main: ./cmd/potctl/main.go
    goos:
      - windows
    goarch:
      - amd64
    ldflags:
      - -s -w -X "github.com/datasance/potctl/pkg/util.versionNumber=v{{.Version}}"
      - -s -w -X "github.com/datasance/potctl/pkg/util.commit={{ .ShortCommit }}"
      - -s -w -X "github.com/datasance/potctl/pkg/util.date={{.Date}}"
      - -s -w -X "github.com/datasance/potctl/pkg/util.platform={{.Os}}/{{.Arch}}"
      - -s -w -X "github.com/datasance/potctl/pkg/util.operatorTag=3.5.1"
      - -s -w -X "github.com/datasance/potctl/pkg/util.routerAdaptorTag=3.5.0"
      - -s -w -X "github.com/datasance/potctl/pkg/util.routerTag=3.5.1"
      - -s -w -X "github.com/datasance/potctl/pkg/util.controllerTag=3.5.6"
      - -s -w -X "github.com/datasance/potctl/pkg/util.agentTag=3.5.2"
      - -s -w -X "github.com/datasance/potctl/pkg/util.controllerVersion=3.5.6"
      - -s -w -X "github.com/datasance/potctl/pkg/util.agentVersion=3.5.2"
      - -s -w -X "github.com/datasance/potctl/pkg/util.repo=ghcr.io/datasance"


archives:
  -
    id: linux
    ids:
      - build_linux
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    formats: [ 'tar.gz' ]
    files:
      - README.md
      - LICENSE
  -
    id: macos
    ids:
      - build_macos
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ if eq .Os `darwin` }}macos{{ else }}{{ .Os }}{{ end }}_{{ .Arch }}"
    formats: [ 'tar.gz' ]
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "{{.ProjectName}}-checksums.txt"

snapshot:
  version_template: "{{ .Version }}-SNAPSHOT"

changelog:
  disable: true
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^dev:'
      - 'README'
      - Merge pull request
      - Merge branch


release:
  github:
    owner: datasance
    name: potctl

  # If set to true, will not auto-publish the release. Default is false.
  draft: false

  # If set to auto, will mark the release as not ready for production
  # in case there is an indicator for this in the tag e.g. v1.0.0-rc1
  # If set to true, will mark the release as not ready for production.
  # Default is false.
  prerelease: auto

brews:
  -
    name: potctl
    homepage: "https://github.com/datasance/potctl"
    description: "CLI for managing Datasance PoT's Distributed Edge Compute clusters"
    goarm: 6

    repository:
      owner: datasance
      name: homebrew-potctl
      

    url_template: "https://github.com/datasance/potctl/releases/download/{{ .Tag }}/{{ .ArtifactName }}"

    commit_author:
      name: emirhandurmus
      email: emirhan.durmus@datasance.com

    directory: Formula

    test: |
      system "#{bin}/potctl version"
    install: |
      bin.install "potctl"
    skip_upload: false

nfpms:
  -
    ids: ['build_linux']
    homepage:  "https://github.com/datasance/potctl"
    description: CLI for managing Datasance PoT's Distributed Edge Compute clusters
    maintainer: Datasance Teknoloji A.S.
    vendor: Datasance


    formats:
      - deb
      - rpm
      - apk

    overrides:
      deb:
        file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
      rpm:
         file_name_template: "{{ .ProjectName }}-{{ .Version }}-1.{{ if eq .Arch `amd64` }}x86_64{{ else if eq .Arch `arm64` }}aarch64{{ else }}{{ .Arch }}{{ end }}{{ if .Arm }}v{{ .Arm }}hl{{ end }}"
      apk:
        file_name_template: "{{ .ConventionalFileName }}"